{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 -- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831\
--   at:        2025-09-15 23:07:02 CLST\
--   site:      Oracle Database 11g\
--   type:      Oracle Database 11g\
\
\
\
-- predefined type, no DDL - MDSYS.SDO_GEOMETRY\
\
-- predefined type, no DDL - XMLTYPE\
\
CREATE TABLE AFP \
    ( \
     id_afp INTEGER  NOT NULL , \
     nombre CHAR (50 CHAR)  NOT NULL \
    ) \
;\
\
ALTER TABLE AFP \
    ADD CONSTRAINT AFP_PK PRIMARY KEY ( id_afp ) ;\
\
CREATE TABLE ATENCION_DIAGNOSTICO \
    ( \
     ATENCION_MEDICA_id_atencion INTEGER  NOT NULL , \
     DIAGNOSTICO_id_diagnostico  INTEGER  NOT NULL \
    ) \
;\
\
ALTER TABLE ATENCION_DIAGNOSTICO \
    ADD CONSTRAINT ATENCION_DIAGNOSTICO PRIMARY KEY ( ATENCION_MEDICA_id_atencion, DIAGNOSTICO_id_diagnostico ) ;\
\
CREATE TABLE ATENCION_MEDICA \
    ( \
     id_atencion          INTEGER  NOT NULL , \
     id_medico            INTEGER  NOT NULL , \
     fecha_atencion       DATE  NOT NULL , \
     hora_atencion        DATE  NOT NULL , \
     tipo                 CHAR (50 CHAR)  NOT NULL , \
     monto_pagado         INTEGER  NOT NULL , \
     PACIENTE_rut         CHAR \
--  WARNING: CHAR size not specified \
                     NOT NULL , \
     PACIENTE_id_paciente INTEGER  NOT NULL , \
     PAGO_id_pago         INTEGER  NOT NULL \
    ) \
;\
CREATE UNIQUE INDEX ATENCION_MEDICA__IDX ON ATENCION_MEDICA \
    ( \
     PAGO_id_pago ASC \
    ) \
;\
\
ALTER TABLE ATENCION_MEDICA \
    ADD CONSTRAINT ATENCION_MEDICA_PK PRIMARY KEY ( id_atencion ) ;\
\
CREATE TABLE ATENCION_MEDICO \
    ( \
     ATENCION_MEDICA_id_atencion INTEGER  NOT NULL , \
     MEDICO_rut                  CHAR (13 CHAR)  NOT NULL , \
     MEDICO_id_medico            INTEGER  NOT NULL \
    ) \
;\
\
ALTER TABLE ATENCION_MEDICO \
    ADD CONSTRAINT ATENCION_MEDICO PRIMARY KEY ( ATENCION_MEDICA_id_atencion, MEDICO_rut, MEDICO_id_medico ) ;\
\
CREATE TABLE COMUNA \
    ( \
     id_comuna        INTEGER  NOT NULL , \
     nombre           CHAR (50 CHAR)  NOT NULL , \
     REGION_id_region INTEGER  NOT NULL \
    ) \
;\
\
ALTER TABLE COMUNA \
    ADD CONSTRAINT COMUNA_PK PRIMARY KEY ( id_comuna ) ;\
\
CREATE TABLE DIAGNOSTICO \
    ( \
     id_diagnostico INTEGER  NOT NULL , \
     nombre         CHAR (100 CHAR)  NOT NULL \
    ) \
;\
\
ALTER TABLE DIAGNOSTICO \
    ADD CONSTRAINT DIAGNOSTICO_PK PRIMARY KEY ( id_diagnostico ) ;\
\
CREATE TABLE DIRECCION \
    ( \
     id_direccion     INTEGER  NOT NULL , \
     calle            CHAR (100 CHAR)  NOT NULL , \
     numero_calle     INTEGER , \
     COMUNA_id_comuna INTEGER  NOT NULL \
    ) \
;\
\
ALTER TABLE DIRECCION \
    ADD CONSTRAINT DIRECCION_PK PRIMARY KEY ( id_direccion ) ;\
\
CREATE TABLE EFECTIVO \
    ( \
     id_pago INTEGER  NOT NULL \
    ) \
;\
\
ALTER TABLE EFECTIVO \
    ADD CONSTRAINT EFECTIVO_PK PRIMARY KEY ( id_pago ) ;\
\
CREATE TABLE ESPECIALIDAD \
    ( \
     id_especialidad INTEGER  NOT NULL , \
     nombre          CHAR (100 CHAR)  NOT NULL \
    ) \
;\
\
ALTER TABLE ESPECIALIDAD \
    ADD CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY ( id_especialidad ) ;\
\
CREATE TABLE EXAMENES_LABORATORIO \
    ( \
     id_examen    INTEGER  NOT NULL , \
     codigo       CHAR (4 CHAR)  NOT NULL , \
     nombre       CHAR (50 CHAR)  NOT NULL , \
     tipo_muestra CHAR (50 CHAR)  NOT NULL , \
     preparacion  CHAR (50 CHAR)  NOT NULL \
    ) \
;\
\
ALTER TABLE EXAMENES_LABORATORIO \
    ADD CONSTRAINT EXAMENES_LABORATORIO_PK PRIMARY KEY ( id_examen ) ;\
\
CREATE TABLE INSTITUCION_SALUD \
    ( \
     id_institucion INTEGER  NOT NULL , \
     nombre         CHAR (50 CHAR)  NOT NULL , \
     tipo           CHAR (50 CHAR)  NOT NULL \
    ) \
;\
\
ALTER TABLE INSTITUCION_SALUD \
    ADD CONSTRAINT INSTITUCION_SALUD_PK PRIMARY KEY ( id_institucion ) ;\
\
CREATE TABLE MEDICO \
    ( \
     id_medico                        INTEGER  NOT NULL , \
     rut                              CHAR (13 CHAR)  NOT NULL , \
     nombre                           CHAR (50 CHAR)  NOT NULL , \
     fecha_ingreso                    DATE  NOT NULL , \
     especialidad                     CHAR (50 CHAR)  NOT NULL , \
     ESPECIALIDAD_id_especialidad     INTEGER  NOT NULL , \
     MEDICO_rut                       CHAR (13 CHAR) , \
     MEDICO_id_medico                 INTEGER , \
     AFP_id_afp                       INTEGER  NOT NULL , \
--  ERROR: Column name length exceeds maximum allowed length(30) \
     INSTITUCION_SALUD_id_institucion INTEGER  NOT NULL \
    ) \
;\
\
ALTER TABLE MEDICO \
    ADD CONSTRAINT MEDICO_PK PRIMARY KEY ( rut, id_medico ) ;\
\
CREATE TABLE PACIENTE \
    ( \
     id_paciente      INTEGER  NOT NULL , \
     rut              CHAR \
--  WARNING: CHAR size not specified \
                     NOT NULL , \
     tipo_usuario     CHAR (50 CHAR)  NOT NULL , \
     nombre           CHAR (50 CHAR)  NOT NULL , \
     sexo             CHAR (10 CHAR)  NOT NULL , \
     fecha_nacimiento DATE  NOT NULL , \
     numero_contacto  CHAR (9 CHAR)  NOT NULL , \
     diagnostico      CHAR (50 CHAR) \
    ) \
;\
\
ALTER TABLE PACIENTE \
    ADD CONSTRAINT PACIENTE_PK PRIMARY KEY ( rut, id_paciente ) ;\
\
CREATE TABLE PAGO \
    ( \
     id_pago                     INTEGER  NOT NULL , \
     ATENCION_MEDICA_id_atencion INTEGER  NOT NULL \
    ) \
;\
CREATE UNIQUE INDEX PAGO__IDX ON PAGO \
    ( \
     ATENCION_MEDICA_id_atencion ASC \
    ) \
;\
\
ALTER TABLE PAGO \
    ADD CONSTRAINT PAGO_PK PRIMARY KEY ( id_pago ) ;\
\
CREATE TABLE REGION \
    ( \
     id_region INTEGER  NOT NULL , \
     nombre    CHAR (100 CHAR)  NOT NULL \
    ) \
;\
\
ALTER TABLE REGION \
    ADD CONSTRAINT REGION_PK PRIMARY KEY ( id_region ) ;\
\
CREATE TABLE Relation_6 \
    ( \
     DIRECCION_id_direccion INTEGER  NOT NULL , \
     PACIENTE_rut           CHAR \
--  WARNING: CHAR size not specified \
                     NOT NULL , \
     PACIENTE_id_paciente   INTEGER  NOT NULL \
    ) \
;\
\
ALTER TABLE Relation_6 \
    ADD CONSTRAINT Relation_6_PK PRIMARY KEY ( DIRECCION_id_direccion, PACIENTE_rut, PACIENTE_id_paciente ) ;\
\
CREATE TABLE SOLICITUD_EXAMEN \
    ( \
     id_solicitud                   INTEGER  NOT NULL , \
     fecha_solicitud                DATE  NOT NULL , \
     estado                         CHAR (50 CHAR)  NOT NULL , \
     ATENCION_MEDICA_id_atencion    INTEGER  NOT NULL , \
     EXAMENES_LABORATORIO_id_examen INTEGER  NOT NULL \
    ) \
;\
\
ALTER TABLE SOLICITUD_EXAMEN \
    ADD CONSTRAINT SOLICITUD_EXAMEN_PK PRIMARY KEY ( id_solicitud ) ;\
\
CREATE TABLE TARJETA \
    ( \
     id_pago       INTEGER  NOT NULL , \
     tipo          CHAR (50 CHAR)  NOT NULL , \
     numero_cuotas INTEGER \
    ) \
;\
\
ALTER TABLE TARJETA \
    ADD CONSTRAINT TARJETA_PK PRIMARY KEY ( id_pago ) ;\
\
CREATE TABLE TRANSFERENCIA \
    ( \
     id_pago          INTEGER  NOT NULL , \
     id_transferencia INTEGER  NOT NULL , \
     rut_origen       CHAR (13 CHAR)  NOT NULL , \
     rut_destino      CHAR (13 CHAR)  NOT NULL , \
     cuenta_origen    INTEGER  NOT NULL , \
     cuenta_destino   INTEGER  NOT NULL \
    ) \
;\
\
ALTER TABLE TRANSFERENCIA \
    ADD CONSTRAINT TRANSFERENCIA_PK PRIMARY KEY ( id_pago ) ;\
\
ALTER TABLE TRANSFERENCIA \
    ADD CONSTRAINT TRANSFERENCIA_PKv1 UNIQUE ( id_transferencia ) ;\
\
ALTER TABLE ATENCION_MEDICO \
    ADD CONSTRAINT ATENCION_MEDICA_FK FOREIGN KEY \
    ( \
     ATENCION_MEDICA_id_atencion\
    ) \
    REFERENCES ATENCION_MEDICA \
    ( \
     id_atencion\
    ) \
;\
\
ALTER TABLE ATENCION_DIAGNOSTICO \
    ADD CONSTRAINT ATENCION_MEDICA_FKv1 FOREIGN KEY \
    ( \
     ATENCION_MEDICA_id_atencion\
    ) \
    REFERENCES ATENCION_MEDICA \
    ( \
     id_atencion\
    ) \
;\
\
ALTER TABLE ATENCION_MEDICA \
    ADD CONSTRAINT ATENCION_MEDICA_PACIENTE_FK FOREIGN KEY \
    ( \
     PACIENTE_rut,\
     PACIENTE_id_paciente\
    ) \
    REFERENCES PACIENTE \
    ( \
     rut,\
     id_paciente\
    ) \
;\
\
ALTER TABLE ATENCION_MEDICA \
    ADD CONSTRAINT ATENCION_MEDICA_PAGO_FK FOREIGN KEY \
    ( \
     PAGO_id_pago\
    ) \
    REFERENCES PAGO \
    ( \
     id_pago\
    ) \
;\
\
ALTER TABLE COMUNA \
    ADD CONSTRAINT COMUNA_REGION_FK FOREIGN KEY \
    ( \
     REGION_id_region\
    ) \
    REFERENCES REGION \
    ( \
     id_region\
    ) \
;\
\
ALTER TABLE ATENCION_DIAGNOSTICO \
    ADD CONSTRAINT DIAGNOSTICO_FK FOREIGN KEY \
    ( \
     DIAGNOSTICO_id_diagnostico\
    ) \
    REFERENCES DIAGNOSTICO \
    ( \
     id_diagnostico\
    ) \
;\
\
ALTER TABLE DIRECCION \
    ADD CONSTRAINT DIRECCION_COMUNA_FK FOREIGN KEY \
    ( \
     COMUNA_id_comuna\
    ) \
    REFERENCES COMUNA \
    ( \
     id_comuna\
    ) \
;\
\
ALTER TABLE EFECTIVO \
    ADD CONSTRAINT EFECTIVO_PAGO_FK FOREIGN KEY \
    ( \
     id_pago\
    ) \
    REFERENCES PAGO \
    ( \
     id_pago\
    ) \
;\
\
ALTER TABLE MEDICO \
    ADD CONSTRAINT MEDICO_AFP_FK FOREIGN KEY \
    ( \
     AFP_id_afp\
    ) \
    REFERENCES AFP \
    ( \
     id_afp\
    ) \
;\
\
ALTER TABLE MEDICO \
    ADD CONSTRAINT MEDICO_ESPECIALIDAD_FK FOREIGN KEY \
    ( \
     ESPECIALIDAD_id_especialidad\
    ) \
    REFERENCES ESPECIALIDAD \
    ( \
     id_especialidad\
    ) \
;\
\
ALTER TABLE ATENCION_MEDICO \
    ADD CONSTRAINT MEDICO_FK FOREIGN KEY \
    ( \
     MEDICO_rut,\
     MEDICO_id_medico\
    ) \
    REFERENCES MEDICO \
    ( \
     rut,\
     id_medico\
    ) \
;\
\
ALTER TABLE MEDICO \
    ADD CONSTRAINT MEDICO_INSTITUCION_SALUD_FK FOREIGN KEY \
    ( \
     INSTITUCION_SALUD_id_institucion\
    ) \
    REFERENCES INSTITUCION_SALUD \
    ( \
     id_institucion\
    ) \
;\
\
ALTER TABLE MEDICO \
    ADD CONSTRAINT MEDICO_MEDICO_FK FOREIGN KEY \
    ( \
     MEDICO_rut,\
     MEDICO_id_medico\
    ) \
    REFERENCES MEDICO \
    ( \
     rut,\
     id_medico\
    ) \
;\
\
ALTER TABLE PAGO \
    ADD CONSTRAINT PAGO_ATENCION_MEDICA_FK FOREIGN KEY \
    ( \
     ATENCION_MEDICA_id_atencion\
    ) \
    REFERENCES ATENCION_MEDICA \
    ( \
     id_atencion\
    ) \
;\
\
ALTER TABLE Relation_6 \
    ADD CONSTRAINT Relation_6_DIRECCION_FK FOREIGN KEY \
    ( \
     DIRECCION_id_direccion\
    ) \
    REFERENCES DIRECCION \
    ( \
     id_direccion\
    ) \
;\
\
ALTER TABLE Relation_6 \
    ADD CONSTRAINT Relation_6_PACIENTE_FK FOREIGN KEY \
    ( \
     PACIENTE_rut,\
     PACIENTE_id_paciente\
    ) \
    REFERENCES PACIENTE \
    ( \
     rut,\
     id_paciente\
    ) \
;\
\
--  ERROR: FK name length exceeds maximum allowed length(30) \
ALTER TABLE SOLICITUD_EXAMEN \
    ADD CONSTRAINT SOLICITUD_EXAMEN_ATENCION_MEDICA_FK FOREIGN KEY \
    ( \
     ATENCION_MEDICA_id_atencion\
    ) \
    REFERENCES ATENCION_MEDICA \
    ( \
     id_atencion\
    ) \
;\
\
--  ERROR: FK name length exceeds maximum allowed length(30) \
ALTER TABLE SOLICITUD_EXAMEN \
    ADD CONSTRAINT SOLICITUD_EXAMEN_EXAMENES_LABORATORIO_FK FOREIGN KEY \
    ( \
     EXAMENES_LABORATORIO_id_examen\
    ) \
    REFERENCES EXAMENES_LABORATORIO \
    ( \
     id_examen\
    ) \
;\
\
ALTER TABLE TARJETA \
    ADD CONSTRAINT TARJETA_PAGO_FK FOREIGN KEY \
    ( \
     id_pago\
    ) \
    REFERENCES PAGO \
    ( \
     id_pago\
    ) \
;\
\
ALTER TABLE TRANSFERENCIA \
    ADD CONSTRAINT TRANSFERENCIA_PAGO_FK FOREIGN KEY \
    ( \
     id_pago\
    ) \
    REFERENCES PAGO \
    ( \
     id_pago\
    ) \
;\
\
CREATE OR REPLACE TRIGGER FKNTM_ATENCION_DIAGNOSTICO \
BEFORE UPDATE OF ATENCION_MEDICA_id_atencion, DIAGNOSTICO_id_diagnostico \
ON ATENCION_DIAGNOSTICO \
BEGIN \
  raise_application_error(-20225,'Non Transferable FK constraint  on table ATENCION_DIAGNOSTICO is violated'); \
END; \
/\
\
CREATE OR REPLACE TRIGGER FKNTM_ATENCION_MEDICA \
BEFORE UPDATE OF PACIENTE_rut, PACIENTE_id_paciente, PAGO_id_pago \
ON ATENCION_MEDICA \
BEGIN \
  raise_application_error(-20225,'Non Transferable FK constraint  on table ATENCION_MEDICA is violated'); \
END; \
/\
\
CREATE OR REPLACE TRIGGER FKNTM_ATENCION_MEDICO \
BEFORE UPDATE OF ATENCION_MEDICA_id_atencion, MEDICO_rut, MEDICO_id_medico \
ON ATENCION_MEDICO \
BEGIN \
  raise_application_error(-20225,'Non Transferable FK constraint  on table ATENCION_MEDICO is violated'); \
END; \
/\
\
CREATE OR REPLACE TRIGGER FKNTM_COMUNA \
BEFORE UPDATE OF REGION_id_region \
ON COMUNA \
BEGIN \
  raise_application_error(-20225,'Non Transferable FK constraint  on table COMUNA is violated'); \
END; \
/\
\
CREATE OR REPLACE TRIGGER FKNTM_DIRECCION \
BEFORE UPDATE OF COMUNA_id_comuna \
ON DIRECCION \
BEGIN \
  raise_application_error(-20225,'Non Transferable FK constraint  on table DIRECCION is violated'); \
END; \
/\
\
CREATE OR REPLACE TRIGGER FKNTO_MEDICO \
BEFORE UPDATE OF MEDICO_rut, MEDICO_id_medico \
ON MEDICO \
FOR EACH ROW \
BEGIN \
 IF :old.MEDICO_rut IS NOT NULL THEN \
  raise_application_error(-20225,'Non Transferable FK constraint MEDICO_MEDICO_FK on table MEDICO is violated'); \
 END IF; \
 IF :old.MEDICO_id_medico IS NOT NULL THEN \
  raise_application_error(-20225,'Non Transferable FK constraint MEDICO_MEDICO_FK on table MEDICO is violated'); \
 END IF; \
END; \
/\
\
CREATE OR REPLACE TRIGGER FKNTM_MEDICO \
BEFORE UPDATE OF AFP_id_afp, INSTITUCION_SALUD_id_institucion, ESPECIALIDAD_id_especialidad \
ON MEDICO \
BEGIN \
  raise_application_error(-20225,'Non Transferable FK constraint  on table MEDICO is violated'); \
END; \
/\
\
CREATE OR REPLACE TRIGGER FKNTM_PAGO \
BEFORE UPDATE OF ATENCION_MEDICA_id_atencion \
ON PAGO \
BEGIN \
  raise_application_error(-20225,'Non Transferable FK constraint  on table PAGO is violated'); \
END; \
/\
\
CREATE OR REPLACE TRIGGER FKNTM_Relation_6 \
BEFORE UPDATE OF DIRECCION_id_direccion, PACIENTE_rut, PACIENTE_id_paciente \
ON Relation_6 \
BEGIN \
  raise_application_error(-20225,'Non Transferable FK constraint  on table Relation_6 is violated'); \
END; \
/\
\
CREATE OR REPLACE TRIGGER FKNTM_SOLICITUD_EXAMEN \
BEFORE UPDATE OF ATENCION_MEDICA_id_atencion, EXAMENES_LABORATORIO_id_examen \
ON SOLICITUD_EXAMEN \
BEGIN \
  raise_application_error(-20225,'Non Transferable FK constraint  on table SOLICITUD_EXAMEN is violated'); \
END; \
/\
\
--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated \
\
--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated \
\
--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated\
\
\
\
-- Oracle SQL Developer Data Modeler Summary Report: \
-- \
-- CREATE TABLE                            19\
-- CREATE INDEX                             2\
-- ALTER TABLE                             40\
-- CREATE VIEW                              0\
-- ALTER VIEW                               0\
-- CREATE PACKAGE                           0\
-- CREATE PACKAGE BODY                      0\
-- CREATE PROCEDURE                         0\
-- CREATE FUNCTION                          0\
-- CREATE TRIGGER                          10\
-- ALTER TRIGGER                            0\
-- CREATE COLLECTION TYPE                   0\
-- CREATE STRUCTURED TYPE                   0\
-- CREATE STRUCTURED TYPE BODY              0\
-- CREATE CLUSTER                           0\
-- CREATE CONTEXT                           0\
-- CREATE DATABASE                          0\
-- CREATE DIMENSION                         0\
-- CREATE DIRECTORY                         0\
-- CREATE DISK GROUP                        0\
-- CREATE ROLE                              0\
-- CREATE ROLLBACK SEGMENT                  0\
-- CREATE SEQUENCE                          0\
-- CREATE MATERIALIZED VIEW                 0\
-- CREATE MATERIALIZED VIEW LOG             0\
-- CREATE SYNONYM                           0\
-- CREATE TABLESPACE                        0\
-- CREATE USER                              0\
-- \
-- DROP TABLESPACE                          0\
-- DROP DATABASE                            0\
-- \
-- REDACTION POLICY                         0\
-- \
-- ORDS DROP SCHEMA                         0\
-- ORDS ENABLE SCHEMA                       0\
-- ORDS ENABLE OBJECT                       0\
-- \
-- ERRORS                                   6\
-- WARNINGS                                 3\
}